### PR TITLE
ansiblee-operator config

### PR DESCRIPTION
**Pull request by raukadah**
Signed-off-by: Chandan Kumar (raukadah) <raukadah@gmail.com>

### CODE REVIEW

**Comment by raukadah** [comment]
@rlandy @viroel @jlarriba @Sandeepyadav93 please have a look, thank you :-)

**Comment by viroel** [comment]
Looks correct, [/openstack-k8s-operators-ansibleee-operator-main-presubmits.yaml](https://github.com/tripleo-ci/release/pull/1/files#diff-14143971a6fb3660581dd9dfc21369e2da5ff600bc934db00900ede4684d7af1) should be auto generated  so don't need review, and prow will check that for you when you propose a PR to openshift/release

**Comment by raukadah** [comment]
@viroel In this review https://github.com/openshift/release/commit/bf2915d3bec95a7f34f94d34fb63e29290742873. 3 OWNERS files were added, Do I also need to add the same?

**Comment by viroel** [comment]
@raukadah yes, you need to add them.
Also, you need a OWNERS file on your repo too, e.g:
https://github.com/openstack-k8s-operators/keystone-operator/commit/0047a3df305b367f07089108f91e737cbe73c9d7

**Comment by jlarriba** [comment]
Its great to see the CI being built from scratch. Good work @raukadah

**Comment by raukadah** [comment]
Thank you everyone for the reviews, I have moved this pr https://github.com/openshift/release/pull/34299 and added the owner file here: https://github.com/openstack-k8s-operators/ansibleee-operator/pull/17 .

**Pull request closed without merging**
